version: '3.8'

services:
  api:
    build:
      context: ./api/chartsData  
    container_name: django-api
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    container_name: nextjs-frontend
    ports:
      - "3000:3000"

 
