# Generated by Django 5.1.1 on 2024-09-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candlestickdata',
            name='date',
            field=models.DateField(),
        ),
    ]
